apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-dev1
commonLabels:
  app.kubernetes.io/instance: staging-dev1
  app.kubernetes.io/managed-by: flux
  toolkit.fluxcd.io/tenant: staging-dev1
resources:
- deployment-web.yaml
#- pv.yaml
- service-db.yaml
- service-web.yaml
- statefulset-db.yaml
