---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack-config
  namespace: monitoring
spec:
  interval: 1m0s
  path: ./monitoring/configs/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux2-monitoring
