---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 1m0s
  path: ./monitoring/controllers/loki-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux2-monitoring
