apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/dev1
namePrefix: staging-
namespace: staging-dev1
commonLabels:
  app.kubernetes.io/instance: staging-dev1
  app.kubernetes.io/managed-by: flux
  toolkit.fluxcd.io/tenant: staging-dev1
patches:
  - path: patch-flux-kustomization.yaml
    target:
      kind: Kustomization
  - path: patch-role-binding.yaml
    target:
      kind: RoleBinding
  # - path: patch-network-policy.yaml
  #   target:
  #     kind: NetworkPolicy
