apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dev1
spec:
  path: ./app-deployment/staging-dev1
  prune: true
  serviceAccountName: staging-dev1-sa
  sourceRef:
    name: staging-dev1-spring-music
